services:
    database:
        name: PostgreSQL
        description: The backend database
        triggeredBy:
            - postEnvironmentStart
        commands:
            start: 'docker run --rm -t --name database postgres:latest'
    redis:
        name: Redis
        description: Our message bus
        triggeredBy:
            - postEnvironmentStart
        commands:
            start: >-
                docker run --rm -t --name redis -p 6379:6379
                redis/redis-stack-server:latest
    backend:
        name: Application Backend
        description: The application backend
        triggeredBy:
            - postEnvironmentStart
        commands:
            start: cd backend && go run main.go

tasks:
    buildAll:
        name: Build All
        description: builds all code
        command: go build .
    runUnitTests:
        name: Runs unit tests
        command: go test -v ./...
    validate:
        name: Validate
        description: Builds and tests the code
        triggeredBy:
            - postEnvironmentStart
        dependsOn:
            - buildAll
            - runUnitTests
